name: Build

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: build-env
          create-args: >-
            python=3.10
            pip=24.0
            jupyterlab
            ipywidgets
            nodejs=20

      - name: Install dependencies
        shell: bash -l {0}
        run: python -m pip install -U "jupyterlite-core==0.6.0rc0" "jupyterlite-xeus==4.0.0b1"

      - name: Build the extension
        shell: bash -l {0}
        run: |
          set -eux
          npm install
          npm run build:all:dev
          python -m pip install -e .

      - name: Build the lite site
        shell: bash -l {0}
        run: |
          set -eux
          npm run build:demo

      - name: Upload artifact
        id: upload-jupyterlite-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./demo/_output
          retention-days: 30

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
